### CREATE COACH - OK -
POST http://localhost:3000/api/coaches
Content-Type: application/json 

{
    "firstName": "Paco",
    "lastName": "Perez"
}

### GET ALL COACHES - OK -
GET  http://localhost:3000/api/coaches

### CREATE PLAYER - OK -
POST http://localhost:3000/api/players
Content-Type: application/json

{
    "firstName": "fabricio",
    "lastName": "Zancolargo",
    "skillfulFoot": "Right"
}

### GET ALL PLAYERS - OK -
GET http://localhost:3000/api/players
